### ISSUE TITLE
User interface is too large when viewed on desktop devices

### ISSUE THREAD

**Issue by DeathPacito6** [Rayz9989/wholsumvalues#5]
When this page is viewed on a desktop, everything is excessively large. 
Is it possible that the website layout has been designed around a mobile only interface?

**Comment by Rayz9989** [comment]
I've experienced this with many other github tests, since there's a common
source code, I don't think we can make the website optimal for all screens,
so it's best if you decrease the zoom on your browser for the webpage,
that's what I've been doing.
